config/routes.rb
Rails.application.routes.draw do
  resources :podcasts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'podcasts#landing'

  get 'home' => 'podcasts#home'
  get 'about_qpc' => 'podcasts#about_qpc'
  get 'episodes' => 'podcasts#episodes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/podcasts_controller.rb
require 'rubygems'
require 'rss/2.0'
require 'open-uri'

class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def episodes
   
  
    @rss = RSS::Parser.parse('https://mooseandqpc.podomatic.com/rss2.xml')
    # puts @rss.items[0].inspect
  end
  
  def landing
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:name, :description, :upload_date)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QpcPodcast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('qpcpodcastpng.png'), :rel => 'icon', :type =>  'qpcpodcastpng.png' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to "QPC", root_path, class: "navbar-brand", style: "color:red; font-family:Goudy Old Style;" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
      
        <li class="nav-item active">
          <a class="nav-link" href="home">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="about_qpc">About QPC</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="episodes">Episodes</a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
    

  
  <div id="justpushtobottom"> 
</div>

<footer class="footer p-t-1 bg-dark" >
        <%# <div class="container">
            <div class="pull-right">
                <nav class="navbar" style="background:transparent; color: black;">
                    <nav class="nav navbar-nav pull-xs-left">
                        <a class="nav-item nav-link" href="#">Home</a>
                        <a class="nav-item nav-link" href="#">About</a>
                        <a class="nav-item nav-link" href="#">Download App</a>
                        <a class="nav-item nav-link" href="#">Help</a>
                    </nav>
                </nav>
            </div> %>
          <center>
            <a href="https://www.facebook.com/QPCTv-752840761589207/"><i class="fa fa-facebook-official fa-2x"></i></a>
            <%# <a href="#"><i class="fa fa-pinterest-p fa-2x"></i></a>
            <a href="#"><i class="fa fa-twitter fa-2x"></i></a> %>
            <a href="https://github.com/qpc4ever"><i class="fa fa-github fa-2x"></i></a>
            <a href="https://www.linkedin.com/in/chris-mcglynn-73614714a/"><i class="fa fa-linkedin fa-2x"></i></a>

            <p class="h6">
                
                <a href="https://cmcglynn.a2hosted.com/" target="_blank">&copy 2018 QPC</a>
            </p>
            </center>
        <%# </div> %>
    </footer>
  </body>
</html>

app/views/podcasts/_form.html.erb
<%= form_with(model: podcast, local: true) do |form| %>
  <% if podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% podcast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :upload_date %>
    <%= form.datetime_select :upload_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/podcasts/about_qpc.html.erb
<h1 style="text-align:center">About QPC</h1>

<p  style="text-align:center; color:white; margin-left:260px; margin-right:260px">QPC is a Musician, Audio Engineer, Software Developer,
 and local radio personality. QPC has been in several bands including Demolition, Bush hogg,
 and Soul Stalkaz, as well as engineered many albums for local bands. He has also been the 
 music editor for the arrival magazine out of Winston Salem NC, and has since resumed the 
 role of software engineer for the magazine. Through MCing events, and doing video interviews with
 bands and local personalities, QPC has amassed a wide audience of die hards, eager for his eunique
 brand of humor and intelect. Weather it's a discussion about a parallel universe, or pro rasslin,
 or music, or the latest conspiracy theories, his banter is always sure to entertain. QPC started 
 his broadcasting career in 2005 when he started co hosting MOOSES MONSTER METAL show with local DJ
 "Moose". With the addition of QPC, Mooses monster metal show became insanely popular. So popular that the duo 
 started their own podcast in 2013 with QPC taking the role of host with Moose as his side kick.
 After a 9 year run together, Moose needed a break and decided to take a hiatus from broadcasting, 
 leaving QPC to fend for himself. Unsure how to proceed, Q did one show by himself, anouncing that he 
 was looking for guests or a possible co host on that first podcast. He got a huge response of people 
 chomping at the bit to take part in his comical, absurd, and intelectual conversation, and 
 the format of QPC's KICK ASS PODCAST was born.</p> 

app/views/podcasts/edit.html.erb
<h1>Editing Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/episodes.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Episodes</h1>
<% @rss.items.each do |item|%>
<div class="container text-center">
    <div class="row" style="margin-left:410px;" >
      <div id="article-div" class="col-xs-12">
        <div class= "well well-lg" >
          <div class= "article-title text-center" >
            <p ><a  href='<%=item.link %>'><%=item.title %></a></p>
            <div style="margin-right:px;">
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
   <% end %>

app/views/podcasts/home.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center">QPC's KICK ASS PODCAST</h1>

<p style="text-align:center;  color:white; margin-left:260px; margin-right:260px">QPC's KICK ASS PODCAST is a hilariously obnoxious, controversial,
and informative podcast about ghosts, aliens, bigfoot, conspiracy theories, pop colture, music, 
pro rasslin, and life. With co host Thomas Leinbach, and a revolving door of special guests each week 
including some of the triads best musicians and most interesting personalities, you're sure to 
love this show !!!</p>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner pic rounded" >
    <div class="carousel-item active">
      <img class="d-block w-100 " src='<%=image_url "16681925_1245615952181315_9160547303181800383_n.jpg"%>' alt="First slide">
    </div> 
    <div class="carousel-item">
      <img class="d-block w-100"  src='<%=image_url "18446753_1945794438779861_4166134926143125890_n.jpg"%>' alt="Second slide">
    </div> 
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "12963618_10209369321609572_2325472657674710604_n.jpg"%>' alt="Third slide">
    </div> 
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "11825163_860155267394054_4655144080423442164_n.jpg"%>' alt="Fourth slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "539113_512524012157183_869217368_n.jpg"%>' alt="Fifth slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "11351257_879723845407316_1876038022363033837_n.jpg"%>' alt="Sixth slide">
    </div>
     <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "18447146_1945794265446545_4419522419037673289_n.jpg"%>' alt="Seventh slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "17264849_1264028877006689_818518656542307044_n.jpg"%>' alt="Eighth slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "18301815_1537713566284915_7860886868805182894_n.jpg"%>' alt="Ninth slide">
    </div>
     <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "18519630_1945794905446481_3720589914522450062_n.jpg"%>' alt="Tenth slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src='<%=image_url "18557270_1432376066783401_7379644359432631571_n.jpg"%>' alt="Eleventh slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  
    <%# <ol class ="carousel-indicators">
      <li> data-target ="#myCarousel" data-slide-to ="0" class="active"</li>
      <li> data-target ="#myCarousel" data-slide-to ="1"</li>
      <li> data-target ="#myCarousel" data-slide-to ="2"</li>
    </ol> %>

   

app/views/podcasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Podcasts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Upload date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @podcasts.each do |podcast| %>
      <tr>
        <td><%= podcast.name %></td>
        <td><%= podcast.description %></td>
        <td><%= podcast.upload_date %></td>
        <td><%= link_to 'Show', podcast %></td>
        <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
        <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/landing.html.erb
<%= favicon_link_tag asset_path('qpcpodcastpng.png'), :rel => 'icon', :type =>  'image/png' %>
<div style="background-color:black" class="container";>
<div class="row" style=" margin-left:240px;">
<div class="col-md-4 col-xs-6 ">
<%= link_to 'home' do %>
    <%= image_tag 'qpcpodcastpng.png',  alt: 'a face that is unnervingly happy', class:"img-fluid"%>
<% end %>
</div>
</div>
</div>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form', podcast: @podcast %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @podcast.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @podcast.description %>
</p>

<p>
  <strong>Upload date:</strong>
  <%= @podcast.upload_date %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>